import{a as v,S as b,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&i(d)}).observe(document,{childList:!0,subtree:!0});function t(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function i(e){if(e.ep)return;e.ep=!0;const s=t(e);fetch(e.href,s)}})();async function g(o,r){return(await v.get("https://pixabay.com/api/",{params:{key:"53361036-d6c3e8b24991f3de089666c85",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:p,page:r}})).data}const u=new b(".gallery-item a");function y(o){const r=o.map(t=>`<li class="gallery-item">
            <a href="${t.largeImageURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
            </a>
            <div class="gallery-desc-box">
                <p class="gallery-desc-title">Likes
                    <span class="gallery-desc">${t.likes}</span></p>
                <p class="gallery-desc-title">Views
                    <span class="gallery-desc">${t.views}</span></p>
                <p class="gallery-desc-title">Comments
                    <span class="gallery-desc">${t.comments}</span></p>
                <p class="gallery-desc-title">Downloads
                    <span class="gallery-desc">${t.downloads}</span></p>
            </div>
        </li>`).join("");a.galleryList.insertAdjacentHTML("beforeend",r),u.options.captionsData="alt",u.refresh()}function w(){a.galleryList.innerHTML=""}function h(){a.loader.classList.remove("hidden")}function f(){a.loader.classList.add("hidden")}function m(){a.loadMore.classList.remove("hidden")}function c(){a.loadMore.classList.add("hidden")}const a={form:document.querySelector(".form"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".more-btn")},p=15;let L,l=1;a.form.addEventListener("submit",async o=>{o.preventDefault();const r=o.target.elements.search.value.trim();if(L=r,!r){n.error({message:"The input field is empty. Please enter your query !",position:"topRight"});return}l>=1&&(c(),l=1),w(),h();try{const t=await g(r,l),i=t.hits;if(console.log(t),i.length===0)n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});else{y(i);const e=t.totalHits,s=Math.ceil(e/p);l===s?(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c()):m()}}catch(t){console.error(t),n.error({message:"Sorry! We can't find that page. It may have been deleted or moved.",position:"topRight"})}f(),a.form.reset()});a.loadMore.addEventListener("click",async()=>{c(),h(),l++;try{const o=await g(L,l),r=o.hits;r.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(r),m());const t=a.galleryList.firstElementChild.getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"});const i=o.totalHits,e=Math.ceil(i/p);l===e&&(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),c())}catch(o){console.error(o),n.error({message:"Sorry! We can't find that page. It may have been deleted or moved.",position:"topRight"})}f()});
//# sourceMappingURL=index.js.map
