import{a as w,S as b,i as c}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();async function p(s,r){return(await w.get("https://pixabay.com/api/",{params:{key:"53361036-d6c3e8b24991f3de089666c85",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:r}})).data}const u=new b(".gallery-item a");function y(s){const r=s.map(e=>`<li class="gallery-item">
            <a href="${e.largeImageURL}">
            <img class="gallery-image" src="${e.webformatURL}" alt="${e.tags}">
            </a>
            <div class="gallery-desc-box">
                <p class="gallery-desc-title">Likes
                    <span class="gallery-desc">${e.likes}</span></p>
                <p class="gallery-desc-title">Views
                    <span class="gallery-desc">${e.views}</span></p>
                <p class="gallery-desc-title">Comments
                    <span class="gallery-desc">${e.comments}</span></p>
                <p class="gallery-desc-title">Downloads
                    <span class="gallery-desc">${e.downloads}</span></p>
            </div>
        </li>`).join("");a.galleryList.insertAdjacentHTML("beforeend",r),u.options.captionsData="alt",u.refresh()}function v(){a.galleryList.innerHTML=""}function f(){a.loader.classList.remove("hidden")}function g(){a.loader.classList.add("hidden")}function m(){a.loadMore.classList.remove("hidden")}function d(){a.loadMore.classList.add("hidden")}const a={form:document.querySelector(".form"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".more-btn")},h=15;let L,l=1;a.form.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements.search.value.trim();if(L=r,!r){c.error({message:"The input field is empty. Please enter your query !",position:"topRight"});return}v(),f(),l>=1&&(d(),l=1);try{const e=await p(r,l);e.hits.length===0?c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):m();const i=e.hits;y(i)}catch(e){console.error(e)}g(),a.form.reset()});a.loadMore.addEventListener("click",async()=>{d(),f(),l++;try{const s=await p(L,l),r=s.hits;y(r);const e=a.galleryList.firstElementChild.getBoundingClientRect();window.scrollBy({top:e.height*2,behavior:"smooth"});const i=s.totalHits,t=Math.ceil(i/h);l===t&&(c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d()),m()}catch(s){console.error(s)}a.loadMore.className!=="hidden"&&g()});
//# sourceMappingURL=index.js.map
