import{a as v,S as b,i as n}from"./assets/vendor-CNqCr-V-.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const c of o.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&i(c)}).observe(document,{childList:!0,subtree:!0});function t(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(e){if(e.ep)return;e.ep=!0;const o=t(e);fetch(e.href,o)}})();async function u(s,r){return(await v.get("https://pixabay.com/api/",{params:{key:"53361036-d6c3e8b24991f3de089666c85",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:h,page:r}})).data}const p=new b(".gallery-item a");function y(s){const r=s.map(t=>`<li class="gallery-item">
            <a href="${t.largeImageURL}">
            <img class="gallery-image" src="${t.webformatURL}" alt="${t.tags}">
            </a>
            <div class="gallery-desc-box">
                <p class="gallery-desc-title">Likes
                    <span class="gallery-desc">${t.likes}</span></p>
                <p class="gallery-desc-title">Views
                    <span class="gallery-desc">${t.views}</span></p>
                <p class="gallery-desc-title">Comments
                    <span class="gallery-desc">${t.comments}</span></p>
                <p class="gallery-desc-title">Downloads
                    <span class="gallery-desc">${t.downloads}</span></p>
            </div>
        </li>`).join("");a.galleryList.insertAdjacentHTML("beforeend",r),p.options.captionsData="alt",p.refresh()}function w(){a.galleryList.innerHTML=""}function g(){a.loader.classList.remove("hidden")}function m(){a.loader.classList.add("hidden")}function f(){a.loadMore.classList.remove("hidden")}function d(){a.loadMore.classList.add("hidden")}const a={form:document.querySelector(".form"),galleryList:document.querySelector(".gallery"),loader:document.querySelector(".loader"),loadMore:document.querySelector(".more-btn")},h=15;let L,l=1;a.form.addEventListener("submit",async s=>{s.preventDefault();const r=s.target.elements.search.value.trim();if(L=r,!r){n.error({message:"The input field is empty. Please enter your query !",position:"topRight"});return}w(),g(),l>=1&&(d(),l=1);try{const i=(await u(r,l)).hits;i.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(i),f())}catch(t){console.error(t),n.error({message:"Sorry! We can't find that page. It may have been deleted or moved.",position:"topRight"})}m(),a.form.reset()});a.loadMore.addEventListener("click",async()=>{d(),g(),l++;try{const s=await u(L,l),r=s.hits;r.length===0?n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}):(y(r),f());const t=a.galleryList.firstElementChild.getBoundingClientRect();window.scrollBy({top:t.height*2,behavior:"smooth"});const i=s.totalHits,e=Math.ceil(i/h);l===e&&(n.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),d())}catch(s){console.error(s),n.error({message:"Sorry! We can't find that page. It may have been deleted or moved.",position:"topRight"})}m()});
//# sourceMappingURL=index.js.map
